### ISSUE TITLE
License issue 

### ISSUE THREAD

**Issue by kaldoran** [mike-rankin/GPS_Board#1]
Hi,

I just open this issue in order to contact you, just to ask which license is used on this project ?

I've found that someone did use your work and sells it.
I'm pretty sure that's the same code.

I'm aware that this project is a free one (and open source one), but just want to warn you ( and be sure that you are aware of this ).

https://www.youtube.com/channel/UCUmCZoMcWxP52QOVUZDohQA
For exemple : https://www.youtube.com/watch?v=Qx85nVWnhTI
https://www.tindie.com/products/PhoenixCNC/olediuno-gps-cube/

If you are the author of the project and the guy behind those video and this shop, sorry for bothering you and thanks for sharing the code. 

Ps : You can close / delete this issue once you have seen it.

**Comment by mike-rankin** [comment]
I'm not familiar with licenses but happy to see someone improving , modifying or selling the open source project that I once worked on with the help of others.

**Comment by kaldoran** [comment]
Thanks for the reply, that was just out of information in case of ;) 
Thanks for the quick reply. And thanks for sharing
